<?php
// Write CSS in chunks to avoid timeout
$chunks = [
    '/* ===== MykaelTech — Global Styles ===== */',
    '',
    ':root {',
    '    --brand-50: #ecfeff;',
    '    --brand-100: #cffafe;',
    '    --brand-200: #a5f3fc;',
    '    --brand-300: #67e8f9;',
    '    --brand-400: #22d3ee;',
    '    --brand-500: #06b6d4;',
    '    --brand-600: #0891b2;',
    '    --brand-700: #0e7490;',
    '    --brand-800: #155e75;',
    '    --brand-900: #164e63;',
    '    --violet-400: #a78bfa;',
    '    --violet-500: #8b5cf6;',
    '    --violet-600: #7c3aed;',
    '}',
    '',
    '* { margin: 0; padding: 0; box-sizing: border-box; }',
    'html { scroll-behavior: smooth; }',
    '',
    'body {',
    '    font-family: "Inter", system-ui, -apple-system, sans-serif;',
    '    background-color: #020617;',
    '    color: #e2e8f0;',
    '    line-height: 1.6;',
    '    -webkit-font-smoothing: antialiased;',
    '    -moz-osx-font-smoothing: grayscale;',
    '}',
    '',
    'h1, h2, h3, h4, h5, h6 {',
    '    font-weight: 700;',
    '    line-height: 1.2;',
    '    color: #fff;',
    '}',
    '',
    '.text-gradient {',
    '    background: linear-gradient(135deg, #22d3ee 0%, #a78bfa 100%);',
    '    -webkit-background-clip: text;',
    '    -webkit-text-fill-color: transparent;',
    '    background-clip: text;',
    '}',
    '',
    '.glass {',
    '    background: rgba(255, 255, 255, 0.04);',
    '    backdrop-filter: blur(20px);',
    '    -webkit-backdrop-filter: blur(20px);',
    '    border: 1px solid rgba(255, 255, 255, 0.06);',
    '}',
    '',
    '.glass-strong {',
    '    background: rgba(255, 255, 255, 0.07);',
    '    backdrop-filter: blur(24px);',
    '    -webkit-backdrop-filter: blur(24px);',
    '    border: 1px solid rgba(255, 255, 255, 0.1);',
    '}',
    '',
    '.bg-glow { position: relative; overflow: hidden; }',
    '.bg-glow::before {',
    '    content: "";',
    '    position: absolute;',
    '    width: 600px; height: 600px;',
    '    border-radius: 50%;',
    '    background: radial-gradient(circle, rgba(34, 211, 238, 0.15) 0%, transparent 70%);',
    '    top: -200px; left: 50%;',
    '    transform: translateX(-50%);',
    '    pointer-events: none; z-index: 0;',
    '}',
    '.bg-glow::after {',
    '    content: "";',
    '    position: absolute;',
    '    width: 400px; height: 400px;',
    '    border-radius: 50%;',
    '    background: radial-gradient(circle, rgba(139, 92, 246, 0.1) 0%, transparent 70%);',
    '    bottom: -100px; right: -100px;',
    '    pointer-events: none; z-index: 0;',
    '}',
    '.bg-glow > * { position: relative; z-index: 1; }',
    '',
    '.card-hover { transition: all 0.35s cubic-bezier(0.4, 0, 0.2, 1); }',
    '.card-hover:hover {',
    '    transform: translateY(-4px);',
    '    border-color: rgba(34, 211, 238, 0.25);',
    '    box-shadow: 0 20px 40px -12px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(34, 211, 238, 0.1);',
    '}',
    '',
    '.btn {',
    '    display: inline-flex; align-items: center; justify-content: center;',
    '    gap: 0.5rem; padding: 0.625rem 1.25rem;',
    '    border-radius: 0.625rem; font-weight: 600; font-size: 0.875rem;',
    '    transition: all 0.2s ease; cursor: pointer; border: none; text-decoration: none;',
    '}',
    '.btn-primary {',
    '    background: linear-gradient(135deg, #0891b2, #7c3aed);',
    '    color: #fff; box-shadow: 0 4px 14px rgba(6, 182, 212, 0.3);',
    '}',
    '.btn-primary:hover {',
    '    box-shadow: 0 6px 20px rgba(6, 182, 212, 0.45);',
    '    transform: translateY(-1px);',
    '}',
    '.btn-secondary {',
    '    background: rgba(255, 255, 255, 0.06); color: #e2e8f0;',
    '    border: 1px solid rgba(255, 255, 255, 0.1);',
    '}',
    '.btn-secondary:hover {',
    '    background: rgba(255, 255, 255, 0.1);',
    '    border-color: rgba(255, 255, 255, 0.2);',
    '}',
    '.btn-ghost {',
    '    background: transparent; color: #94a3b8; border: none;',
    '}',
    '.btn-ghost:hover { color: #22d3ee; background: rgba(34, 211, 238, 0.08); }',
    '',
    'input[type="email"], input[type="text"], input[type="password"],',
    'input[type="search"], textarea, select {',
    '    width: 100%; padding: 0.625rem 0.875rem;',
    '    background: #1e293b;',
    '    border: 1px solid rgba(255, 255, 255, 0.1);',
    '    border-radius: 0.5rem; color: #f1f5f9; font-size: 0.875rem;',
    '    transition: all 0.2s ease; outline: none;',
    '}',
    'input:focus, textarea:focus, select:focus {',
    '    border-color: #22d3ee;',
    '    box-shadow: 0 0 0 3px rgba(34, 211, 238, 0.15);',
    '}',
    'input::placeholder, textarea::placeholder { color: #64748b; }',
    '',
    '::-webkit-scrollbar { width: 8px; height: 8px; }',
    '::-webkit-scrollbar-track { background: #0f172a; }',
    '::-webkit-scrollbar-thumb { background: #334155; border-radius: 4px; }',
    '::-webkit-scrollbar-thumb:hover { background: #475569; }',
    '',
    '::selection { background: rgba(34, 211, 238, 0.3); color: #fff; }',
    '',
    '::focus-visible { outline: 2px solid #22d3ee; outline-offset: 2px; }',
];

// Combine and write
$css = implode("\n", $chunks);
file_put_contents('resources/css/app.css', $css);
echo "CSS chunk 1 written: " . strlen($css) . " bytes\n";